server:
  port: 7788 #服务端口
spring:
  application:
    name: microservice-config-server #指定服务名
  cloud:
    config:
      server:
        git: #配置git仓库地址
          uri: https://gitee.com/hkpmayun/myspconfig.git
          search-paths:
            - myspringcloudconfig		#配置文件目录地址
          username: 17788122886
          password: peng123* 	#码云密码（公有项目不需要设置）
      label: master	#分支名称
  rabbitmq:
    host: 192.168.3.11
    port: 5673
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://hkp:123456@127.0.0.1:8100/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: microservice-config-server
management:
  endpoints:
    web:
      exposure:
        include: '*'